# This workflow will build a .NET project and deploy a Docker image to GHCR
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Building Recipe Nest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installing Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Building project
      run: dotnet build --no-restore
